---
- name: Update Servers Using Package Managers
  hosts: all
  become: true
  gather_facts: true
  vars:
  - ansible_connection: ssh

  tasks:

  - name: Update RHEL Based Systems
    dnf:
      name: "*"
      state: latest
    when: ansible_facts['os_family'] == "RedHat" or
          ansible_facts['os_family'] == "AlmaLinux"

  - name: Autoremove Unneeded Packages On RHEL Based Systems
    dnf:
      autoremove: yes
    when: ansible_facts['os_family'] == "RedHat" or
          ansible_facts['os_family'] == "AlmaLinux"

  - name: Clean DNF Cache on RHEL Based Systems
    command: 'dnf clean all'
    when: ansible_facts['os_family'] == "RedHat" or
          ansible_facts['os_family'] == "AlmaLinux"

  - name: Update Debian Based Systems
    apt:
      name: "*"
      state: latest
    when: ansible_facts['os_family'] == "Debian"
          
  - name: Autoremove Unneeded Packages And Clean Cache On Debian Based Systems
    apt:
      autoremove: yes
      autoclean: yes
    when: ansible_facts['os_family'] == "Debian"

- name: Reboot Appropriate Devices
  hosts: vms, !no_reboot
  become: true
  gather_facts: false
  vars:
  - ansible_connection: ssh

  tasks:

  - name: Reboot VMs
    reboot: